### PR TITLE
fix: add missing spaces

### LINKED ISSUE #11: Whitespace is sometimes deleted before/after code or italics
E.g., around `ggplot2` in this reprex:

``` r
test <- tempfile(fileext = ".Rmd")

writeLines(
  "R has well-developed plotting capabilities, and the `ggplot2` package is one of, if not the most powerful pieces of plotting software available today. We will begin learning to use `ggplot2` in the next episode.",
  test
)

aeolus::unleash(test)

readLines(test)
#> [1] "R has well-developed plotting capabilities, and the `ggplot2`package is one of, if not the most powerful pieces of plotting software available today."
#> [2] "We will begin learning to use`ggplot2` in the next episode."                                                                                          
#> [3] ""                                                                                                                                                     
#> [4] ""
```

<sup>Created on 2025-07-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

(Also, extra blank trailing lines are added and might be removed to minimize diffs.)

### PR DESCRIPTION
**Pull request by maelle**
Fix #11

### CODE REVIEW

**Review by Bisaloo — APPROVED** [review]
This seems to be working great. Thanks!

File: R/unleash.R [hunk 1]
```diff
@@ -100,3 +130,27 @@ handle_text <- function(text) {
...
+    perl = TRUE
+  ))
+  if (length(sentences) < 2) {
+    return(xml2::xml_text(xml_node))
+  }
+  # now we have to put back together the punctuation that was split
+  punctuations <- which(sentences %in% c(".", "!", "?"))
+  punctuations <- setdiff(punctuations, 1)
+
+  for (i in seq_len(length(punctuations))) {
```
Comment (Bisaloo) [inline R/unleash.R]:
```suggestion
  for (i in seq_along(punctuations)) {
```

?
